// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | `/_favicon/?${string}`
    | "/_locales/en/messages.json"
    | "/_locales/ja/messages.json"
    | "/background.js"
    | "/content-extractor.js"
    | "/content-scripts/content.js"
    | "/data/models-dev-openai-compatible.json"
    | "/icons/icon128.png"
    | "/icons/icon16.png"
    | "/icons/icon48.png"
    | "/offscreen.html"
    | "/options.html"
    | "/permissions.html"
    | "/popup.html"
    | "/PRIVACY.md"
    | "/utils/trustDb/bloomfilter-vendor.mjs"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
