/**
 * storage/defaults.ts
 * デフォルト設定定数
 * storage.tsからDEFAULT_SETTINGSを分離したモジュール
 */

import { StorageKeys } from './types.js';
import type { Settings } from './types.js';

export const DEFAULT_SETTINGS: Settings = {
    [StorageKeys.OBSIDIAN_API_KEY]: '',
    [StorageKeys.OBSIDIAN_PROTOCOL]: 'https',
    [StorageKeys.OBSIDIAN_PORT]: '27124',
    [StorageKeys.MIN_VISIT_DURATION]: 5,
    [StorageKeys.MIN_SCROLL_DEPTH]: 50,
    [StorageKeys.GEMINI_API_KEY]: '',
    [StorageKeys.GEMINI_MODEL]: 'gemini-1.5-flash',
    [StorageKeys.OBSIDIAN_DAILY_PATH]: '092.Daily',
    [StorageKeys.AI_PROVIDER]: 'openai',
    [StorageKeys.OPENAI_BASE_URL]: 'https://api.groq.com/openai/v1',
    [StorageKeys.OPENAI_API_KEY]: '',
    [StorageKeys.OPENAI_MODEL]: 'openai/gpt-oss-20b',
    [StorageKeys.OPENAI_2_BASE_URL]: 'http://127.0.0.1:11434/v1',
    [StorageKeys.OPENAI_2_API_KEY]: '',
    [StorageKeys.OPENAI_2_MODEL]: 'llama3',
    [StorageKeys.LM_STUDIO_BASE_URL]: 'http://127.0.0.1:1234/v1',
    [StorageKeys.LM_STUDIO_MODEL]: '',
    [StorageKeys.OLLAMA_BASE_URL]: 'http://localhost:11434/v1',
    [StorageKeys.OLLAMA_MODEL]: '',
    [StorageKeys.PROVIDER_TYPE]: '',
    [StorageKeys.PROVIDER_BASE_URL]: '',
    [StorageKeys.PROVIDER_API_KEY]: '',
    [StorageKeys.PROVIDER_MODEL]: '',
    [StorageKeys.DOMAIN_WHITELIST]: [],
    [StorageKeys.DOMAIN_BLACKLIST]: [
        'amazon.co.jp', 'amazon.com', 'yahoo.co.jp', 'yahoo.com',
        'facebook.com', 'twitter.com', 'x.com', 'instagram.com',
        'youtube.com', 'google.com', 'google.co.jp'
    ],
    [StorageKeys.DOMAIN_FILTER_MODE]: 'blacklist',
    [StorageKeys.PRIVACY_MODE]: 'masked_cloud',
    [StorageKeys.PII_CONFIRMATION_UI]: true,
    [StorageKeys.PII_SANITIZE_LOGS]: true,
    [StorageKeys.AUTO_SAVE_PRIVACY_BEHAVIOR]: 'save',
    [StorageKeys.CONTENT_STRIP_HARD_ENABLED]: true,
    [StorageKeys.CONTENT_STRIP_KEYWORDS]: ['balance', 'account', 'meisai', 'login', 'card-number', 'keiyaku', 'password', 'payment', 'transaction', 'billing', 'invoice', 'receipt', 'rireki', 'torihiki', 'zandaka', 'hoken', 'address'],
    [StorageKeys.CONTENT_STRIP_KEYWORD_ENABLED]: true,
    [StorageKeys.UBLOCK_RULES]: { blockDomains: [], exceptionDomains: [], metadata: { importedAt: 0, ruleCount: 0 } },
    [StorageKeys.UBLOCK_SOURCES]: [],
    [StorageKeys.UBLOCK_FORMAT_ENABLED]: false,
    [StorageKeys.SIMPLE_FORMAT_ENABLED]: true,
    [StorageKeys.ALLOWED_URLS]: [],
    [StorageKeys.ALLOWED_URLS_HASH]: '',
    [StorageKeys.CUSTOM_PROMPTS]: [],
    [StorageKeys.DOMAIN_FILTER_CACHE]: [],
    [StorageKeys.DOMAIN_FILTER_CACHE_TIMESTAMP]: 0,
    [StorageKeys.MP_PROTECTION_ENABLED]: false,
    [StorageKeys.MP_ENCRYPT_API_KEYS]: false,
    [StorageKeys.MP_ENCRYPT_ON_EXPORT]: false,
    [StorageKeys.MP_REQUIRE_ON_IMPORT]: false,
    [StorageKeys.TAG_CATEGORIES]: [],
    [StorageKeys.TAG_SUMMARY_MODE]: false,
    [StorageKeys.L0_EXTRACTIVE_ENABLED]: true,
    [StorageKeys.L0_EXTRACTIVE_TOP_K]: 10,
    [StorageKeys.L0_EXTRACTIVE_MIN_LENGTH]: 20,
    [StorageKeys.L0_EXTRACTIVE_SIMILARITY_THRESHOLD]: 0.3,
    [StorageKeys.L0_EXTRACTIVE_PERFORMANCE_THRESHOLD]: 1000,
    [StorageKeys.PRIVACY_CONSENT]: false,
    [StorageKeys.AUTO_CONTENT_FETCH_ENABLED]: false,
    [StorageKeys.ALERT_FINANCE]: true,
    [StorageKeys.ALERT_SENSITIVE]: true,
    [StorageKeys.ALERT_UNVERIFIED]: false,
    [StorageKeys.SAVE_ABORTED_PAGES]: false,
    [StorageKeys.SAFETY_MODE]: 'balanced',
    [StorageKeys.TRANCO_TIER]: 'top10k',
    [StorageKeys.DENIED_DOMAINS]: {},
    [StorageKeys.PERMISSION_NOTIFY_THRESHOLD]: 3,
    [StorageKeys.CONDITIONAL_CSP_ENABLED]: true,
    [StorageKeys.CONDITIONAL_CSP_PROVIDERS]: [],
    [StorageKeys.MAX_TOKENS_PER_PROMPT]: 1000,
    [StorageKeys.AI_TIMEOUT_MS]: 0,
    [StorageKeys.SKIP_AI_RATE_LIMIT_MAX]: 5,
    [StorageKeys.SKIP_AI_RATE_LIMIT_WINDOW_MS]: 60000,
    [StorageKeys.AI_SUMMARY_CLEANSING_ENABLED]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_ALT]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_METADATA]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_ADS]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_NAV]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_SOCIAL]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_DEEP]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_LINK_DENSITY]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_JSON_LD]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_LAZY_LOAD]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_SKIP_LINK]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_CARD]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_FIXED]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_RECOMMEND]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_PAGINATION]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_SNS_PROMO]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_POPUP]: true,
    [StorageKeys.AI_SUMMARY_CLEANSING_PLATFORM]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_TEXT_DENSITY]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_SHORT_SEQ]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_SYMBOL_LINE]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_LINK_PARA]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_ENHANCED_HIDDEN]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_EMPTY_ELEM]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_JP_LAYOUT]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_JP_NAVIGATION]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_AUTHOR]: false,
    [StorageKeys.AI_SUMMARY_CLEANSING_LINK_RATIO_THRESHOLD]: 70,
    [StorageKeys.AI_SUMMARY_CLEANSING_SHORT_TEXT_THRESHOLD]: 30,
    [StorageKeys.AI_SUMMARY_CLEANSING_SHORT_SEQ_COUNT]: 5,
    [StorageKeys.AI_SUMMARY_CLEANSING_LINK_PARA_THRESHOLD]: 50,
    [StorageKeys.AI_SUMMARY_CLEANSING_CUSTOM_PATTERNS]: [],
    [StorageKeys.TRANCO_VERSION]: '',
    [StorageKeys.TRANCO_DOMAINS]: [],
    [StorageKeys.TRANCO_NOTIFICATION_SHOWN]: null,
    [StorageKeys.TRANCO_CONSENT_GRANTED]: null,
    [StorageKeys.TRANCO_CONSENT_DENIED_REASON]: null,
    [StorageKeys.TRANCO_CONSENT_DENIED_TIMESTAMP]: null,
    [StorageKeys.AI_USAGE_MONTH]: '',
    [StorageKeys.AI_USAGE_TOKENS_SENT]: 0,
    [StorageKeys.AI_USAGE_TOKENS_RECEIVED]: 0,
    [StorageKeys.AI_USAGE_REQUEST_COUNT]: 0,
    [StorageKeys.AI_RATE_LIMIT_WINDOW_START]: 0,
    [StorageKeys.AI_RATE_LIMIT_COUNT]: 0,
    [StorageKeys.CONTENT_DEDUP_ENABLED]: true,
    [StorageKeys.CONTENT_DEDUP_THRESHOLD]: 0.7,
    [StorageKeys.SUMMARY_NORMALIZE_ENABLED]: true
};